### ISSUE TITLE
Estatuto de Igualdade 

### ISSUE THREAD

**Issue by nighto** [nighto/brasil-portugal#6]

**Comment by LucasCaixeta** [comment]
É possivel ter o Cartão do Cidadão Portugues mesmo não sendo Portugues, através do Tratado de Porto Seguro, o qual provê igualdade de direitos para quem o solicitar.

### Documentos necessários:

1. Uma cópia do Título de Residência - Válido.;
2. Declaração de nacionalidade Brasileira para o tratado de porto seguro, obtido no consulado (grátis, mediante agendamento);
3.  [Fromulário de solicitação do SEF](https://imigrante.sef.pt/wp-content/uploads/Requerimento_DireitosDeveres_DD_PT.pdf). Imprima e preencha da forma mais legivel possível.
4. Mande para o endereço da imagem abaixo:
![image](https://user-images.githubusercontent.com/408965/91441497-3617e580-e868-11ea-9eda-6ae9d2c1269c.png)
5. Espere até 5 meses para receber 2 cartas de confirmação, uma do SEF e outra da conservatória (confirmando que saiu no diário oficial tuga);
6. Va ao IRN (loja do cidadão) com os papéis que chegaram + seus documentos (titulo, nif, niss, utente - todos vão ser adicionados no cartao do cidadão) - uns 40 euros pra solicitar.
7. Pegue em 1 semana (média)

### _Vantagens:_

- Facilita financiamento de casa/carro (podendo assim financiar em até 90% a casa e 100% o carro);
- Se quiser fazer mestrado/doutorado vai pagar a mesma propina (mensalidade) que tugas.
