### ISSUE TITLE
Questionamento sobre assinatura digital no Contrato de Trabalho/Promessa de Contrato de Trabalho.

### ISSUE THREAD

**Issue by luanpcweb** [nighto/brasil-portugal#66]
Segundo o [checklist](https://www.vfsglobal.com/portugal/Brazil/pdf/D3.pdf), o contrato ou promessa de contratro de trabalho deverá ser válido. Com a possíbilidade de realizar a assinatura virtal alguém já tentou o processo de visto enviando um contrato assinado digitalmente?

**Comment by joaoclaudioone** [comment]
Sim, a minha promessa de contrato foi assinada usando a plataforma docusign. Assim como o contrato assinado dessa maneira foi válido para apresentar no SEF para a autorização de residência.

**Comment by nighto** [comment]
Boa, vou alterar o texto para deixar claro que serve assinado fisicamente ou digitalmente.

**Comment by gabrielgambarra** [comment]
Meu visto chegou há pouco tempo. 

Promessa foi assinada pelo docusign também, mas quando a documentação chegou no consulado do Rio, pediram que fosse reconhecida assinatura da responsável pela empresa em cartório.
