### ISSUE TITLE
Reagrupamento Familiar - Comprovante de União

### ISSUE THREAD

**Issue by leonardoloch** [nighto/brasil-portugal#67]
Olá a todos,
Gostaria de saber se para comprovar a união poderia ser o documento de União Estável, porém com uma data menor de dois anos o reconhecimento?

**Comment by nighto** [comment]
Olá @leonardoloch , vi que fechou a issue, chegou a alguma conclusão? Se sim seria interessante incluir no texto para as futuras pessoas que possam ter essa dúvida.

**Comment by leonardoloch** [comment]
Pelo que andei pesquisando precisa mesmo ser uma data maior que dois anos, e a união estável não tem como ser retroativa, logo só começa a valer a partir da dada que foi reconhecida, ou o caso seria o casamento mesmo, já que não tem tempo mínimo.
