### ISSUE TITLE
Apostila de Haia Eletrônica (Apostil)

### ISSUE THREAD

**Issue by fthomasvp** [nighto/brasil-portugal#73]
Olá!

Gostaria de agradecer pelas informações compartilhadas nesse repositório.

No dia 03 de Junho de 2022, o CNJ liberou a execução do Apostilamento de Haia através da plataforma [apostil.org.br](https://apostil.org.br/).

Sabes dizer se Portugal aceita a versão **Eletrônica** da Apostila de Haia?
Ou é melhor ir a um cartório e solicitar o apostilamento para evitar problemas?

Obrigado.

**Comment by fthomasvp** [comment]
Entrei em contato com a Embaixada de Portugal aqui no Brasil e eles informaram que todos os documentos brasileiros devem ser apostilados em um cartório de notas.

**Comment by nighto** [comment]
Portugal infelizmente ainda não consta na [lista de países signatários da apostila eletrônica](https://assets.hcch.net/docs/b697a1f1-13be-47a0-ab7e-96fcb750ed29.pdf).
