### ISSUE TITLE
Morar em Portugal por mais de 1 ano, trabalhando remoto CLT para empresa no Brasil, é possível?

### ISSUE THREAD

**Issue by flavionn** [nighto/brasil-portugal#79]
Olá. Muito obrigado por todas as informações disponíveis neste repo.

**Dúvida**
Existe algum visto que me permita morar em Portugal por mais de 1 ano, trabalhando remoto CLT para uma empresa no Brasil? Se sim, qual?

**Comment by PauloGoncalvesBH** [comment]
No último dia 30 de setembro o governo de Portugal emitiu um decreto que vai tornar possível o que você deseja com o novo tipo de visto chamado "Visto de estada temporária e de autorização de residência para nómadas digitais". **Esse decreto vai começar a valer apenas no dia 30 de outubro**.

A notícia sobre essa nova regulamentação: https://www.portugal.gov.pt/pt/gc23/comunicacao/noticia?i=alteracoes-a-lei-dos-estrangeiros-simplifica-procedimentos

O decreto caso queira ver com mais detalhes (pesquise por _Artigo 18.º -B_): https://files.dre.pt/1s/2022/09/19000/0002800097.pdf

E no dia 30 de outubro recomendo você abrir a legispédia do SEF, que é o material oficial do SEF sobre a legislação, para ver se atualizaram com os dados do decreto: https://sites.google.com/site/leximigratoria/lei-de-estrangeiros---indice
