### ISSUE TITLE
Modelo de Carta de Intenção

### ISSUE THREAD

**Issue by andersonwarren** [nighto/brasil-portugal#88]
Pessoal, mandei meu processo para a VFS e eles me pediram uma carta de intenção, alguém precisou enviar essa carta? Tem algum modelo que devo seguir?

**Comment by PauloGoncalvesBH** [comment]
oi @andersonwarren, tem mais contexto? Que tipo de visto está tentando que pediram essa carta?

**Comment by nighto** [comment]
+1, também não me lembro de ter precisado desse documento para o visto D3, mas tb já faz 4 anos que apliquei, vai que alguma coisa mudou de lá pra cá.

**Comment by joaoclaudioone** [comment]
@andersonwarren, acredito que carta de intenção é um documento para visto de estudante. Você precisa falar um pouco sobre a sua trajetória acadêmica e de como você acha que ao estudar naquela instituição. Se for esse o seu contexto. 
Também vi que é um documento que estão pedindo para o visto de procura de trabalho, não sei se é o seu caso.

**Comment by nighto** [comment]
Obrigado!

**Comment by andersonwarren** [comment]
Conforme combinado, segue um modelo de carta de intenção.

[Carta_Intenção_Modelo.docx](https://github.com/nighto/brasil-portugal/files/11520258/Carta_Intencao_Modelo.docx)
